Repository atlp-rwanda/Dev-Pulse-BN, pull requests merged in 2021-08, with the labels that each got.

#10 adds and deletes authorized emails
  package.json
  src/controllers/authController.js
  src/controllers/mailListController.js
  src/database/migrations/20210803043632-create-allowed-emails.js
  src/database/models/allowedemails.js
  src/database/seeders/20210803050146-allowedEmails.js
  src/helpers/response.js
  src/routes/allowedEmailsRouter.js
  src/routes/index.js
  src/services/allowedEmailsService.js
  src/services/userService.js
  src/swagger/emails/allowedEmails.js
  src/swagger/index.js
  src/validation/allowedEmailsValidation.js
  src/validation/schema/index.js
Labels: Ready

#8 add programs and cohorts
  src/controllers/cohortsController.js
  src/controllers/programsController.js
  src/controllers/ratingController.js
  src/controllers/userController.js
  src/database/migrations/20191018140915-create-average-rating.js
  src/database/migrations/20210802153340-create-cohorts.js
  src/database/migrations/20210802154320-create-programms.js
  src/database/migrations/20210802154414-alter_users_table.js
  src/database/migrations/20210802155802-alter_ratings_table.js
  src/database/models/cohort.js
  src/database/models/program.js
  src/database/models/rating.js
  src/database/models/user.js
  src/middlewares/cohort.js
  src/middlewares/users.js
  src/routes/cohortsRoute.js
  src/routes/index.js
  src/routes/programsRouter.js
  src/routes/ratingRouter.js
  src/routes/userRoutes.js
  src/services/cohortService.js
  src/services/programsService.js
  src/services/ratingService.js
  src/services/userService.js
  src/swagger/cohorts/cohort.js
  src/swagger/index.js
  src/swagger/programs/programs.js
  src/swagger/users/users.js
  src/validation/cohortsValidator.js
  src/validation/programsValidator.js
Labels: WIP

#12 feat(ratings): compute program rating
  .eslintrc.json
  .prettierrc.json
  package.json
  src/controllers/ratingController.js
  src/helpers/index.js
  src/middlewares/users.js
  src/services/programsService.js
  src/services/ratingService.js
Labels: Ready, feature

#15 Ft authorized email list
  src/controllers/mailListController.js
  src/routes/allowedEmailsRouter.js
  src/services/allowedEmailsService.js
  src/swagger/emails/allowedEmails.js
Labels: Ready
